steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - '--no-cache'
      - '-t'
      - '$_DEPLOY_REGION-$_GCR_HOSTNAME/$PROJECT_ID/multiproadmin/web_app:$COMMIT_SHA'
      - .
      - '-f'
      - Dockerfile
    id: Build
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - '$_DEPLOY_REGION-$_GCR_HOSTNAME/$PROJECT_ID/multiproadmin/web_app:$COMMIT_SHA'
    id: Push
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk:slim'
    args:
      - beta
      - run
      - deploy
      - web_app
      - '--platform=managed'
      - '--image=$_DEPLOY_REGION-$_GCR_HOSTNAME/$PROJECT_ID/multiproadmin/web_app:$COMMIT_SHA'
      
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID,$_LABELS
      - '--region=$_DEPLOY_REGION'
      - '--quiet'
    id: Deploy
    entrypoint: gcloud
images:
  - '$_DEPLOY_REGION-$_GCR_HOSTNAME/$PROJECT_ID/multiproadmin/web_app:$COMMIT_SHA'
options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY
tags:
  - gcp-cloud-build-deploy-cloud-run
  - gcp-cloud-build-deploy-cloud-run-managed
  - backend